# Generated by Django 4.2.16 on 2024-09-10 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.TextField(help_text='Name of the video')),
                ('video_path', models.TextField(help_text='Path for the video saved in the local server')),
            ],
            options={
                'db_table': 'VideoModel1',
            },
        ),
        migrations.CreateModel(
            name='VideoModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.TextField(help_text='Name of the video')),
                ('video_file', models.FileField(upload_to='video')),
            ],
            options={
                'db_table': 'VideoModel2',
            },
        ),
    ]
