# Generated by Django 4.2.16 on 2024-09-19 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VideoExtractor', '0002_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subtitles',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='subtitles',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subtitles',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='subtitles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitles',
            name='language',
            field=models.TextField(default='subtitles/default.srt'),
            preserve_default=False,
        ),
    ]
