# Generated by Django 4.2.16 on 2024-09-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoExtractor', '0003_remove_subtitles_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitles',
            old_name='language',
            new_name='languages',
        ),
    ]
