# Generated by Django 4.2.16 on 2024-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoExtractor', '0005_alter_subtitles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='start_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
